### ISSUE TITLE
Small bug causing sending >2048 tokens to cohere api

### ISSUE THREAD

**Issue by joeltorby** [ellenealds/streamlit_template_cohere_semantic_search#1]
This issue appeared when I replicated this project for our own guides, which probably are a bit longer than cohere's guides in the example.

The issue by sending to long messages (with too many tokens) to Cohere api is solved by changing: 

> text

to 

> text_chunk

on main.py at row 81. This change also makes a clear speed up of the script :) 

https://github.com/ellenealds/streamlit_template_cohere_semantic_search/blob/main/main.py#L81

**Comment by ellenealds** [comment]
Great spot, thank you so much for your support and contribution
